// auth
export const SIGNIN_POST = 'SIGNIN_POST'
export const SIGNIN_FETCHING = 'SIGNIN_FETCHING'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAILED = 'SIGNIN_FAILED'

export const SIGNUP_POST = 'SIGNUP_POST'
export const SIGNUP_FETCHING = 'SIGNUP_FETCHING'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILED = 'SIGNUP_FAILED'