// create
export const CREATE_POST = 'CREATE_POST'
export const CREATE_POST_FETCHING = 'CREATE_POST_FETCHING'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAILED = 'CREATE_POST_FAILED'